<a href="https://colab.research.google.com/github/wjdqlsdlsp/AI_using_pytorch/blob/main/nn_Module%EB%A1%9C_%EA%B5%AC%ED%98%84%ED%95%98%EB%8A%94_%EC%84%A0%ED%98%95%ED%9A%8C%EA%B7%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

In [3]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

# model = nn.Linear(input_dim, output_dim)
model = nn.Linear(1,1)

print(list(model.parameters()))

[Parameter containing:
tensor([[0.8325]], requires_grad=True), Parameter containing:
tensor([0.6215], requires_grad=True)]


In [4]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) 

nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 3.844363
Epoch  100/2000 Cost: 0.080185
Epoch  200/2000 Cost: 0.049550
Epoch  300/2000 Cost: 0.030619
Epoch  400/2000 Cost: 0.018921
Epoch  500/2000 Cost: 0.011692
Epoch  600/2000 Cost: 0.007225
Epoch  700/2000 Cost: 0.004464
Epoch  800/2000 Cost: 0.002759
Epoch  900/2000 Cost: 0.001705
Epoch 1000/2000 Cost: 0.001053
Epoch 1100/2000 Cost: 0.000651
Epoch 1200/2000 Cost: 0.000402
Epoch 1300/2000 Cost: 0.000249
Epoch 1400/2000 Cost: 0.000154
Epoch 1500/2000 Cost: 0.000095
Epoch 1600/2000 Cost: 0.000059
Epoch 1700/2000 Cost: 0.000036
Epoch 1800/2000 Cost: 0.000022
Epoch 1900/2000 Cost: 0.000014
Epoch 2000/2000 Cost: 0.000009


In [5]:
# 임의의 입력 4를 선언
new_var =  torch.FloatTensor([[4.0]]) 
# 입력한 값 4에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) # forward 연산
# y = 2x 이므로 입력이 4라면 y가 8에 가까운 값이 나와야 제대로 학습이 된 것
print("훈련 후 입력이 4일 때의 예측값 :", pred_y) 

훈련 후 입력이 4일 때의 예측값 : tensor([[7.9941]], grad_fn=<AddmmBackward>)


In [6]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9966]], requires_grad=True), Parameter containing:
tensor([0.0077], requires_grad=True)]


In [8]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

# 모델을 선언 및 초기화. 다중 선형 회귀이므로 input_dim=3, output_dim=1.
model = nn.Linear(3,1)

print(list(model.parameters()))

[Parameter containing:
tensor([[-0.2707,  0.3117,  0.1606]], requires_grad=True), Parameter containing:
tensor([0.4470], requires_grad=True)]


In [9]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 

nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 23858.978516
Epoch  100/2000 Cost: 6.595523
Epoch  200/2000 Cost: 6.270781
Epoch  300/2000 Cost: 5.963076
Epoch  400/2000 Cost: 5.671563
Epoch  500/2000 Cost: 5.395337
Epoch  600/2000 Cost: 5.133646
Epoch  700/2000 Cost: 4.885660
Epoch  800/2000 Cost: 4.650689
Epoch  900/2000 Cost: 4.428047
Epoch 1000/2000 Cost: 4.217053
Epoch 1100/2000 Cost: 4.017160
Epoch 1200/2000 Cost: 3.827707
Epoch 1300/2000 Cost: 3.648180
Epoch 1400/2000 Cost: 3.478066
Epoch 1500/2000 Cost: 3.316879
Epoch 1600/2000 Cost: 3.164104
Epoch 1700/2000 Cost: 3.019345
Epoch 1800/2000 Cost: 2.882121
Epoch 1900/2000 Cost: 2.752095
Epoch 2000/2000 Cost: 2.628862
